# Generated by Django 2.0.1 on 2018-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('regtime', models.DateTimeField(verbose_name='注册时间')),
                ('delflag', models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户')], default=1, verbose_name='用户类型标记')),
            ],
        ),
    ]
