# Generated by Django 2.0 on 2018-01-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='评论内容'),
        ),
    ]
