# Generated by Django 2.0 on 2018-01-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20180114_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogin',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
