# Generated by Django 2.0 on 2018-01-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20180114_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='daily',
            field=models.TextField(max_length=100, verbose_name='日志内容'),
        ),
    ]
