DROP TABLE IF EXISTS `USERINFO`;
CREATE TABLE `USERINFO`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USERNAME` VARCHAR(20) NOT NULL,
  `BODY` VARCHAR(300) NOT NULL  COMMENT '内容',
  `PASSWORD` VARCHAR(50) NOT NULL ,
  `CREATED_TIME` DATETIME NOT NULL  ,
  `CATEGORY_ID` INT(3) NOT NULL  COMMENT '分类',
  `DELFLAG` INT(3) NOT NULL  COMMENT '内容',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;