DROP TABLE IF EXISTS `USER_DETAILS`;
CREATE TABLE `USER_DETAILS`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USERINFO_ID` INT(5) NOT NULL,
  `SEX` INT(5),
  `IMG_PATH` VARCHAR(50),
  `BIRTHDAY` VARCHAR(50),
  `PROVINCE` INT(5),
  `CITY` INT(5),
  `MARRIAGE` INT(1),
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;