DROP TABLE IF EXISTS `USERINFO`;
CREATE TABLE `USERINFO`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USERNAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL ,
  `CREATE_TIME` DATETIME NOT NULL  ,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;