#用户自定义分类
DROP TABLE IF EXISTS `USER_CATEGORY`;
CREATE TABLE `USER_CATEGORY`(
  `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USER_LOGIN_ID` INT(5) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;