# Generated by Django 2.0.1 on 2018-01-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('blogname', models.CharField(max_length=30, verbose_name='博客名')),
                ('blogsign', models.CharField(max_length=50, null=True, verbose_name='博客个性签名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('lastlogin', models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录时间')),
                ('name', models.CharField(max_length=16, null=True)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('province', models.CharField(max_length=20, null=True, verbose_name='省份')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='地址')),
                ('birthday', models.CharField(max_length=16, null=True, verbose_name='生日')),
                ('email', models.EmailField(max_length=30, null=True, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('regtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('profile', models.CharField(max_length=200, null=True, verbose_name='简介')),
                ('delflag', models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户')], default=1, verbose_name='用户类型标记')),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.UserInfo'),
        ),
        migrations.AddField(
            model_name='daily',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Category'),
        ),
        migrations.AddField(
            model_name='daily',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myblog.Tag'),
        ),
    ]
