# Generated by Django 2.0.1 on 2018-01-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.UserInfo')),
            ],
        ),
    ]
