# Generated by Django 2.0.1 on 2018-02-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('img', models.CharField(blank=True, max_length=100)),
                ('birthtime', models.DateTimeField(blank=True)),
                ('marriage', models.IntegerField(blank=True, choices=[(0, '单身'), (1, '已婚'), (2, '离异')], verbose_name='婚姻')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.City')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Province')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.UserInfo'),
        ),
        migrations.AddField(
            model_name='city',
            name='provinceCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Province'),
        ),
    ]
