# Generated by Django 2.0.1 on 2018-01-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='blogname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='blogsign',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='lastlogin',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='province',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='tel',
        ),
    ]
