# Generated by Django 2.0.1 on 2018-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.FileField(upload_to='avatar/'),
        ),
    ]
