# Generated by Django 2.0.1 on 2018-01-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20180127_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
    ]
