# Generated by Django 2.0.1 on 2018-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_userinfo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='body',
            field=models.TextField(verbose_name='标题内容'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='modified_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='title',
            field=models.CharField(max_length=70, verbose_name='标题'),
        ),
    ]
