# Generated by Django 2.0.1 on 2018-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20180203_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
