# Generated by Django 2.0.1 on 2018-01-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20180127_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='regtime',
            field=models.DateTimeField(verbose_name='注册时间'),
        ),
    ]
