# Generated by Django 2.0.1 on 2018-02-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20180207_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='province',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
